# Generated by Django 4.0.1 on 2022-01-24 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0004_p_staff_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Proof', models.FileField(default='', upload_to='address-proof')),
            ],
        ),
        migrations.CreateModel(
            name='P_Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Contract', models.FileField(default='', upload_to='contract')),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Experience', models.FileField(default='', upload_to='experience')),
            ],
        ),
        migrations.CreateModel(
            name='P_Handbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Handbook', models.FileField(default='', upload_to='handbook')),
            ],
        ),
        migrations.CreateModel(
            name='P_Insurance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Insurance', models.FileField(default='', upload_to='insurance')),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Photo', models.ImageField(default='', upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='P_Pvg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pvg', models.FileField(default='', upload_to='pvg')),
            ],
        ),
        migrations.CreateModel(
            name='P_Qualification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Qualification', models.FileField(default='', upload_to='qualification')),
            ],
        ),
        migrations.CreateModel(
            name='P_Sssc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Document', models.FileField(default='', upload_to='sssc')),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(default='', max_length=100)),
                ('Username', models.CharField(default='', max_length=100)),
                ('PhoneNumber', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=100)),
                ('SortCode', models.CharField(default='', max_length=100)),
                ('Covidteststatus', models.BooleanField()),
                ('Covid_test_expire_date', models.DateField()),
                ('Sssc_id', models.FileField(default='', upload_to='sssc')),
                ('skills', models.CharField(default='', max_length=100)),
                ('toc', models.CharField(default='', max_length=100)),
                ('Address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_address')),
                ('Contract_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_contract')),
                ('Experience_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_experience')),
                ('Handbook_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_handbook')),
                ('Insurance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_insurance')),
                ('Photo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_photo')),
                ('Pvg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_pvg')),
                ('Qualification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_qualification')),
            ],
        ),
        migrations.CreateModel(
            name='P_Vaccination_certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Certificate', models.FileField(default='', upload_to='vaccine-certificate')),
            ],
        ),
        migrations.CreateModel(
            name='P_Work_permit_certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Permit', models.FileField(default='', upload_to='work-permit')),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='p_staff_details',
            name='P_Staff_id',
        ),
        migrations.DeleteModel(
            name='P_Staff',
        ),
        migrations.DeleteModel(
            name='P_Staff_details',
        ),
        migrations.AddField(
            model_name='p_user',
            name='Vaccination_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_vaccination_certificate'),
        ),
        migrations.AddField(
            model_name='p_user',
            name='Workpermit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_work_permit_certificate'),
        ),
    ]
