# Generated by Django 4.0.1 on 2022-01-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0005_p_address_p_contract_p_experience_p_handbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_photo',
            name='Photo',
        ),
        migrations.AddField(
            model_name='p_photo',
            name='photo',
            field=models.ImageField(default='', upload_to='Photo'),
        ),
    ]
