# Generated by Django 4.0.1 on 2022-01-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0006_remove_p_photo_photo_p_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_photo',
            name='photo',
        ),
        migrations.AddField(
            model_name='p_photo',
            name='Photo',
            field=models.ImageField(default='', upload_to='photo'),
        ),
    ]
