# Generated by Django 4.0.1 on 2022-01-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0007_remove_p_photo_photo_p_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_qualification',
            old_name='Qualification',
            new_name='qualification',
        ),
    ]
