# Generated by Django 4.0.1 on 2022-01-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0008_rename_qualification_p_qualification_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_sssc',
            old_name='Document',
            new_name='document',
        ),
        migrations.AlterField(
            model_name='p_user',
            name='Covid_test_expire_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='p_user',
            name='Covidteststatus',
            field=models.BooleanField(blank=True),
        ),
    ]
