# Generated by Django 4.0.1 on 2022-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0009_rename_document_p_sssc_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_user',
            name='Covidteststatus',
            field=models.CharField(default='', max_length=100),
        ),
    ]
