# Generated by Django 4.0.1 on 2022-01-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0010_alter_p_user_covidteststatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_sssc',
            old_name='document',
            new_name='certificate',
        ),
    ]
