# Generated by Django 4.0.1 on 2022-01-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0014_alter_p_sssc_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_sssc',
            name='expiry_date',
        ),
    ]
