# Generated by Django 4.0.1 on 2022-01-24 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0015_remove_p_sssc_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_sssc',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
