# Generated by Django 4.0.1 on 2022-01-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0020_alter_p_user_covid_test_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_user',
            name='Covid_test_expire_date',
        ),
    ]
