# Generated by Django 4.0.1 on 2022-01-25 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0021_remove_p_user_covid_test_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_user',
            name='Covid_test_expire_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
