# Generated by Django 4.0.1 on 2022-01-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0022_p_user_covid_test_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_user',
            old_name='Covid_test_expire_date',
            new_name='Covidtest_expire_date',
        ),
    ]
