# Generated by Django 4.0.1 on 2022-01-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0025_p_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_contact',
            old_name='Username',
            new_name='Name',
        ),
    ]
