# Generated by Django 4.0.1 on 2022-01-31 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0030_delete_p_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_user',
            old_name='Covidteststatus',
            new_name='Address_1',
        ),
        migrations.RenameField(
            model_name='p_user',
            old_name='Fullname',
            new_name='Address_2',
        ),
        migrations.RenameField(
            model_name='p_user',
            old_name='SortCode',
            new_name='Address_3',
        ),
        migrations.RenameField(
            model_name='p_user',
            old_name='Covid_test_expire_date',
            new_name='Date_of_birth',
        ),
        migrations.RenameField(
            model_name='p_user',
            old_name='Username',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='p_user',
            old_name='skills',
            new_name='Lastname',
        ),
        migrations.RenameField(
            model_name='p_user',
            old_name='toc',
            new_name='postcode',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Address_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Contract_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Experience_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Handbook_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Insurance_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Photo_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Pvg_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Qualification_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Sssc_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Vaccination_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Workpermit_id',
        ),
        migrations.CreateModel(
            name='P_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SortCode', models.CharField(default='', max_length=100)),
                ('Covidteststatus', models.CharField(default='', max_length=100)),
                ('Covid_test_expire_date', models.DateField(blank=True, null=True)),
                ('skills', models.CharField(default='', max_length=100)),
                ('toc', models.CharField(default='', max_length=100)),
                ('Address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_address')),
                ('Contract_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_contract')),
                ('Experience_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_experience')),
                ('Handbook_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_handbook')),
                ('Insurance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_insurance')),
                ('Photo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_photo')),
                ('Pvg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_pvg')),
                ('Qualification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_qualification')),
                ('Sssc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_sssc')),
                ('Vaccination_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_vaccination_certificate')),
                ('Workpermit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_work_permit_certificate')),
            ],
        ),
    ]
