# Generated by Django 4.0.1 on 2022-01-31 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0031_rename_covidteststatus_p_user_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_details',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_user'),
        ),
    ]
