# Generated by Django 4.0.1 on 2022-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0032_p_details_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_user',
            name='otp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
