# Generated by Django 4.0.1 on 2022-02-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0034_p_user_address_id_p_user_contract_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_address',
            name='Proof',
            field=models.FileField(default='', null=True, upload_to='address-proof'),
        ),
        migrations.AlterField(
            model_name='p_contract',
            name='Contract',
            field=models.FileField(default='', null=True, upload_to='contract'),
        ),
        migrations.AlterField(
            model_name='p_experience',
            name='Experience',
            field=models.FileField(default='', null=True, upload_to='experience'),
        ),
        migrations.AlterField(
            model_name='p_handbook',
            name='Handbook',
            field=models.FileField(default='', null=True, upload_to='handbook'),
        ),
        migrations.AlterField(
            model_name='p_insurance',
            name='Insurance',
            field=models.FileField(default='', null=True, upload_to='insurance'),
        ),
        migrations.AlterField(
            model_name='p_photo',
            name='Photo',
            field=models.ImageField(default='', null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='p_pvg',
            name='pvg',
            field=models.FileField(default='', null=True, upload_to='pvg'),
        ),
        migrations.AlterField(
            model_name='p_qualification',
            name='qualification',
            field=models.FileField(default='', null=True, upload_to='qualification'),
        ),
        migrations.AlterField(
            model_name='p_vaccination_certificate',
            name='Certificate',
            field=models.FileField(default='', null=True, upload_to='vaccine-certificate'),
        ),
        migrations.AlterField(
            model_name='p_work_permit_certificate',
            name='Permit',
            field=models.FileField(default='', null=True, upload_to='work-permit'),
        ),
    ]
