# Generated by Django 4.0.1 on 2022-02-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0036_alter_p_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_contact',
            name='Subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
