# Generated by Django 4.0.1 on 2022-02-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0037_p_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_temp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(default='', max_length=100)),
                ('Lastname', models.CharField(default='', max_length=100)),
                ('PhoneNumber', models.CharField(default='', max_length=100)),
                ('Date_of_birth', models.DateField(blank=True, null=True)),
                ('Email', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=100)),
                ('Address_1', models.CharField(default='', max_length=100)),
                ('Address_2', models.CharField(default='', max_length=100)),
                ('Address_3', models.CharField(default='', max_length=100)),
                ('postcode', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
