# Generated by Django 4.0.1 on 2022-02-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0039_user_temp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_temp',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_user'),
        ),
    ]
