# Generated by Django 4.0.1 on 2022-02-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0040_user_temp_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_temp',
            name='User_id',
        ),
    ]
