# Generated by Django 4.0.1 on 2022-02-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0041_remove_user_temp_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_caretaker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phonenumber', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
