# Generated by Django 4.0.1 on 2022-02-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0043_rename_message_p_caretaker_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_user',
            name='Covidteststatus',
        ),
    ]
