# Generated by Django 3.1.4 on 2022-02-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0044_remove_p_user_covidteststatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_CV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cv', models.FileField(default='', null=True, upload_to='qualification')),
            ],
        ),
        migrations.RenameField(
            model_name='p_user',
            old_name='Covid_test_expire_date',
            new_name='booster',
        ),
        migrations.RemoveField(
            model_name='p_experience',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Contract_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Handbook_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Insurance_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Qualification_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='Vaccination_id',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='toc',
        ),
        migrations.AddField(
            model_name='p_experience',
            name='FireSafety',
            field=models.FileField(default='', null=True, upload_to='FireSafety'),
        ),
        migrations.AddField(
            model_name='p_experience',
            name='HealthSafety',
            field=models.FileField(default='', null=True, upload_to='HealthSafety'),
        ),
        migrations.AddField(
            model_name='p_experience',
            name='InfectionControl',
            field=models.FileField(default='', null=True, upload_to='ManualHandling'),
        ),
        migrations.AddField(
            model_name='p_experience',
            name='ManualHandling',
            field=models.FileField(default='', null=True, upload_to='ManualHandling'),
        ),
        migrations.AddField(
            model_name='p_pvg',
            name='pvgno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='p_user',
            name='vaccine1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_user',
            name='vaccine2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='p_contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='P_Contract',
        ),
        migrations.DeleteModel(
            name='P_Handbook',
        ),
        migrations.DeleteModel(
            name='P_Qualification',
        ),
        migrations.DeleteModel(
            name='P_Vaccination_certificate',
        ),
        migrations.AddField(
            model_name='p_user',
            name='Cv_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_cv'),
        ),
    ]
