# Generated by Django 3.1.4 on 2022-02-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0045_auto_20220214_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_user',
            name='AccountNo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='p_user',
            name='NInumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
