# Generated by Django 3.1.4 on 2022-02-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0046_auto_20220214_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_user',
            name='select',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_temp',
            name='select',
            field=models.CharField(default='', max_length=100),
        ),
    ]
