# Generated by Django 3.1.4 on 2022-02-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0049_p_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_user',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
