# Generated by Django 3.1.4 on 2022-02-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0050_p_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_user',
            name='select',
        ),
    ]
