# Generated by Django 3.1.4 on 2022-02-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0052_auto_20220219_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_user',
            name='Workpermit_id',
        ),
    ]
