# Generated by Django 3.1.4 on 2022-02-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0054_remove_p_user_previous_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='P_Work_permit_certificate',
        ),
    ]
