# Generated by Django 3.1.4 on 2022-02-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0055_delete_p_work_permit_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_Work_permit_certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passport', models.FileField(default='', null=True, upload_to='passport')),
                ('visa', models.FileField(default='', null=True, upload_to='visa')),
                ('brp', models.FileField(default='', null=True, upload_to='brp')),
                ('passport_expiry_date', models.DateField()),
                ('visa_expiry_date', models.DateField()),
                ('brp_expiry_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='p_user',
            name='Previous_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_previous_employer'),
        ),
        migrations.AddField(
            model_name='p_user',
            name='workpermit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primecareapp.p_work_permit_certificate'),
        ),
    ]
