# Generated by Django 3.1.4 on 2022-02-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0056_auto_20220221_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_previous_employer',
            name='payslip1',
            field=models.FileField(blank=True, default='', null=True, upload_to='payslip1'),
        ),
        migrations.AlterField(
            model_name='p_previous_employer',
            name='payslip2',
            field=models.FileField(blank=True, default='', null=True, upload_to='payslip2'),
        ),
    ]
