# Generated by Django 3.1.4 on 2022-03-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0058_auto_20220221_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_user',
            name='AccountNo',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='p_user',
            name='Address_3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='p_user',
            name='NInumber',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='p_user',
            name='skills',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='p_user',
            name='status',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
