# Generated by Django 3.1.4 on 2022-03-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primecareapp', '0059_auto_20220309_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_insurance',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='p_sssc',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='p_work_permit_certificate',
            name='brp_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='p_work_permit_certificate',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='p_work_permit_certificate',
            name='visa_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
